n = int(input('Escreva um numero qualquer: '))
print('A tabuada do {} é:'.format(n))
print('{} x 1 = {}'.format(n, (n * 1)), end='  ')
print('{} x 2 = {}'.format(n, (n * 2)))
print('{} x 3 = {}'.format(n, (n * 3)), end=' ')
print('{} x 4 = {}'.format(n, (n * 4)))
print('{} x 5 = {}'.format(n, (n * 5)), end=' ')
print('{} x 6 = {}'.format(n, (n * 6)))
print('{} x 7 = {}'.format(n, (n * 7)), end=' ')
print('{} x 8 = {}'.format(n, (n * 8)))
print('{} x 9 = {}'.format(n, (n * 9)), end=' ')
print('{} x 10 = {}'.format(n, (n * 10)))