nome = str(input('Digite o seu nome completo: ')).strip()
tam = int(len(nome))
space = int(nome.count(' '))
split = nome.split()
print('Analisando o seu nome...')
print('Seu nome todo maiúsculo fica: {}'.format(nome.upper()))
print('Seu nome todo minúsculo fica: {}'.format(nome.lower()))
print('Seu nome completo tem {} letras.'.format(tam - space))
print('Seu primeiro nome tem {} letras.'.format(len(split[0])))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
